### ISSUE TITLE
GTX 1050 no driver

### ISSUE THREAD

**Issue by boirs1234** [dtcu0ng/H81M-DS2-Hackintosh#11]
High Sierra GTX 1050 can't drive

**Comment by dtcu0ng** [comment]
Hi, what is your macOS version first?

**Comment by boirs1234** [comment]
10.13.6 is the image file of olarila.

**Comment by boirs1234** [comment]
https://link-center.net/462274/olarila-highsierra-mf

**Comment by dtcu0ng** [comment]
try update macOS to the latest version via App Store, then install NVIDIA Web Driver (instruction described at README) and add 'nvda_drv_vrl=1' to 'boot-args' under NVRAM > Add

good luck
