### ISSUE TITLE
efi咨询

### ISSUE THREAD

**Issue by kittyzero520** [dtcu0ng/H81M-DS2-Hackintosh#16]
你好
i5 6500 h81主板 可以用这个efi不？

**Comment by dtcu0ng** [comment]
Please describe your issue in English.

**Comment by kittyzero520** [comment]
hello

CPUI: 5 6500

Main board: h81

Can I use this efi?

**Comment by dtcu0ng** [comment]
No, you can't run a Skylake CPU on a Haswell motherboard. Please double-check both your CPU and motherboard, if the numbers start with 4xxx, you can use this EFI. If not, you can't use this EFI.
