### ISSUE TITLE
Copy EFI vào nhưng đang không hoạt động

### ISSUE THREAD

**Issue by quynv186** [dtcu0ng/H81M-DS2-Hackintosh#6]
Bạn cung cấp giúp cấu hình trong bios. Mình copy folder EFI vào nhưng đang không boot được. đang báo lỗi
Nếu mình sử dụng card on-board hoặc HD7850 có được không?

**Comment by dtcu0ng** [comment]
Bạn cung cấp cấu hình mà bạn đang cài đặt nhé, thêm cả lỗi mà đang gặp phải nhé
HD7850 mình không sử dụng nên không biết được, còn sử dụng card onboard thì có thể sử dụng được nếu sử dụng các loại cổng khác với cổng VGA.

**Comment by quynv186** [comment]
Gigabyte H81M-DS2
Core i3-4130
Bios: F2
RAM: 12GB

Trước đây mình dùng Clover cho 10.15. Mình đang muốn cài BigSur cho MacOS mới hơn!

**Comment by dtcu0ng** [comment]
BIOS thì mình bật có mỗi EHCI/XHCI Hand-off thôi, tắt Secure Boot (Windows 8 Mode chuyển sang thành Other OS, disable CSM) và vẫn boot được. Không biết bạn đang có lỗi gì về BIOS nhỉ?

**Comment by namnguyenptitcn** [comment]
Khi disable card onboard trong bios thì boot bị treo. nếu để enable thì chạy qua và màn hình đen, điện ở PC vẫn hoạt động. bạn có config gì chỉ chạy card onboard không?

**Comment by dtcu0ng** [comment]
> Khi disable card onboard trong bios thì boot bị treo. nếu để enable thì chạy qua và màn hình đen, điện ở PC vẫn hoạt động. bạn có config gì chỉ chạy card onboard không?

Xin lỗi vì trả lời 'khá muộn', có lẽ bạn đã tìm được câu trả lời rồi. Theo mình nghĩ để chạy riêng card onboard thì bạn phải patch lại ACPI (tắt card rời dùng card onboard) sau đó dùng config của card onboard thôi.

Ở link bên dưới có 3 cách để tắt card onboard nếu bạn dùng OpenCore bạn tham khảo nhé. Chúc bạn may mắn.

https://dortania.github.io/OpenCore-Install-Guide/extras/spoof.html#disabling-gpu

**Comment by dtcu0ng** [comment]
Một lưu ý thêm là macOS chỉ hỗ trợ xuất hình qua các chuẩn DVI, DisplayPort hoặc HDMI chứ không hỗ trợ VGA. Bạn xem lại mình đã sử dụng đúng chuẩn chưa. Nhiều khả năng cũng do cái này.
